### PR TITLE
Merge in source install method

### PR DESCRIPTION
**Pull request by patcon**
https://github.com/werrett/mosh-cookbook

Seems there's a worthwhile fork with ssh agent forwarding, that has been in limbo for years through various PRs:

https://github.com/mobile-shell/mosh/pull/583
https://github.com/rinne/mosh/branches

Might add this later.

cc: @werrett :)

### CODE REVIEW

**Comment by patcon** [comment]
Any particular way you'd like to be credited @werret? Is metadata and README ok?

**Comment by jtimberman** [comment]
In v0.4.0, I [specifically dropped source installation support](https://github.com/jtimberman/mosh-cookbook/commit/5353a654140986c2d80551fb91d9e1bb430d1d3e). 

I also have since transferred ownership of this cookbook to @brianhays, though only added him to this repo, rather than transfer to him.

**Comment by patcon** [comment]
Thanks jt. I would normally agree, but do feel this is a special situation for mosh, given that one of the biggest feature requests in mosh history is ongoing and unmerged after 3 years, and people are commonly building/using forks.

Any chance of a second opinion @brianhays?

**Comment by patcon** [comment]
For context, this PR allows someone to build from the github fork's archive like so:
https://github.com/patcon/patcon-workstation/blob/master/roles/workstation.json#L17-L21

**Pull request closed without merging**
